<main >
    <div class="center">
        <div class="img">
            <img src="img/page-acessorios.jpg" alt="">
        </div>
        <div class="text">
            <h2>Acessórios para cachorros de passeio: coleira e guia</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            </p>
            <h2>Para uma pelagem mais bonita: escova de pentear!</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>Brinquedos para entreter o seu cãozinho</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            
        </div>
    </div>
</main>