<main >
    <div class="center">
        <div class="img">
            <img src="img/page-banho-tosa.png" alt="">
        </div>
        <div class="text">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h2>O QUE É A TOSA DE CACHORRO?</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h2>QUAIS SÃO OS TIPOS DE TOSA DE CACHORRO?</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA HIGIÊNICA</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA DE RAÇA</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA BEBÊ</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA LEÃO</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA DE MÁQUINA</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>TOSA NA TESOURA</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
        </div>
    </div>
</main>