<main >
    <div class="center">
        <div class="img">
            <img src="img/page-farmacia.jpg" alt="">
        </div>
        <div class="text">
            <h2>MEDICAMENTO VETERINÁRIO PETSONALIZADO</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h2>Formas farmacêuticas</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h2>Sabores</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            
        </div>
    </div>
</main>