<main >
    <div class="center">
        <div class="img">
            <img src="img/page-hospedagem.jpg" alt="">
        </div>
        <div class="text">
            <h2>Onde seu pet ficara hospedado?</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h2>Nossos melhores cuidadores</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>entretenimento e muita diversão</h3>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus quis iusto incidunt ab neque natus error illum veritatis assumenda repellendus nihil repellat minima aliquam ad quia, illo, officia praesentium fugit.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus quis iusto incidunt ab neque natus error illum veritatis assumenda repellendus nihil repellat minima aliquam ad quia, illo, officia praesentium fugit.
            </p>
            
        </div>
    </div>
</main>