<section class="banner">
        <div class="center_banner">
            <div class="info_banner">
                <h1>Cuide do seu pet da melhor forma!</h1>
                <a href="/relatar-problema1">Relatar problema do meu pet</a>
            </div>
            <div class="img_banner">
                <img src="img/banner.png" alt="">
            </div>
        </div>
   </section>
   <section id="servicos" class="servicos">
     <h2>Nossos serviços<hr></h2>
        <div class="servicos_wrap">
            <div class="servicos">
                <div class="box_servico">
                    <div class="img_servico banho_tosa">
                        <h3>Banho e tosa</h3>
                    </div>
                    <div class="box_text">
                        <p> Dar banho regularmente é uma forma de cuidar da saúde de seu pet. Nossos profissionais se dedicam da melhor forma toda sua atenção aos animais a fim de fazer do banho uma experiência divertida.</p>
                    </div>
                    <a href="/servico-banho-e-tosa?servicos">Ver mais</a>
                </div>

                <div class="box_servico">
                    <div class="img_servico veterinario">
                        <h3>Veterinario</h3>
                    </div>
                    <div class="box_text">
                        <p> Na VetsLine você conta com uma clínica especializada, com os melhores profissionais, infraestrutura e equipamentos de ponta, tudo para manter a saúde e bem estar de seu pet.</p>
                    </div>
                    <a href="/servico-veterinario?servicos">Ver mais</a>
                </div>
                
                <div class="box_servico">
                    <div class="img_servico acessorios">
                        <h3>Acessórios</h3>
                    </div>
                    <div class="box_text">
                        <p> Seu pet merece tudo de melhor, brinquedos educativos, acessórios no geral ou itens de segurança. Por esse motivo, opte por acessórios de qualidade que ofereça tudo para o bem-estar do seu pet.</p>
                    </div>
                    <a href="/servico-acessorios?servicos">Ver mais</a>
                </div>

                

                <div class="box_servico">
                    <div class="img_servico farmacia">
                        <h3>Farmácia</h3>
                    </div>
                    <div class="box_text">
                        <p> Quer proporcionar todo o bem-estar que seu amigo precisa? Aqui, na VetsLine, você encontra remédios para seu amiguinho com diferentes finalidades, que proporcionam melhor qualidade de vida.</p>
                    </div>
                    <a href="/servico-farmacia?servicos">Ver mais</a>
                </div>

                <div class="box_servico">
                    <div class="img_servico hospedagem">
                        <h3>Hospedagem</h3>
                    </div>
                    <div class="box_text">
                        <p>Existem vários motivos para um tutor precisar de alguém para cuidar de seus animais de estimação por determinado tempo, portanto, oferecer o serviço de hospedagem em seu petshop pode ser muito vantajoso.</p>
                    </div>
                    <a href="/servico-hospedagem?servicos">Ver mais</a>
                </div>
            </div>
        </div>
   </section>

   <section class="sobre_nos">
        <div class="box_info_local">
            <h3>Onde estamos localizados?</h3>
            <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14634.516114521302!2d-46.43039086044921!3d-23.50986789999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce654f0729faff%3A0x90814f50611adeb9!2zUGV0IFNob3AgVMOjbyBQZXQgUmHDp8O1ZXM!5e0!3m2!1spt-BR!2sbr!4v1674754208268!5m2!1spt-BR!2sbr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <div class="box_sobre_nos">
            <h3>Sobre nós</h3>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste non repellendus, fugit nostrum repudiandae architecto error debitis ratione quidem laboriosam aliquid quas rem reiciendis blanditiis deleniti nobis tempora dolores inventore.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste non repellendus, fugit nostrum repudiandae architecto error debitis ratione quidem laboriosam aliquid quas rem reiciendis blanditiis deleniti nobis tempora dolores inventore.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste non repellendus, fugit nostrum repudiandae architecto error debitis ratione quidem laboriosam aliquid quas rem reiciendis blanditiis deleniti nobis tempora dolores inventore.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste non repellendus, fugit nostrum repudiandae architecto error debitis ratione quidem labor
            </p>
        </div>
   </section>
</body>
</html>