<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="img/logo-Vetsline2.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enviado com sucesso</title>
    <style>
        @font-face {
            font-family: tomy;
            src: url(/css/MADETOMMY.woff);
        }
        *{
            margin: 0;
            padding: 0;
            font-family: tomy;
        }
        html{
            font-size: 62.5%;
        }
        body{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background: #f2f2f2;
        }
        main{
            background: white;
            width: 490px;
            padding: 17px;
            border-radius: 7px;
            box-shadow: 4px 4px 15px rgb(0, 0, 0, .2);
        }
        main h1{
            text-align: center;
            font-size: 2.3rem;
        }
        main  div{
            display: flex;
            justify-content: space-between;
            align-items: centre;
        }
        main a{
            border: 1px solid red;
            display: block;
            text-decoration: none;
            text-align: center;
            background: #ffb600;
            border: none;
            border-radius: 7px;
            font-size: 1.7rem;
            padding: 8px 0;
            width: 55%;
            margin-top: 22px;
            color: #0f0b01;
            box-shadow: inset -2px -2px 10px rgb(0, 0, 0, .2);
            cursor: pointer;
        }
        main div a:first-child{
            width: 40%;
        }
    </style>
</head>
<body>
    <main>
        <h1>Cadastro realizado com secusso</h1>
        <div><a href="/home">Voltar para Home</a><a href="/entrar">Fazer login</a></div>
    </main>
</body>
</html>