<main >
    <div class="center">
        <div class="img logo">
            <img src="img/VetsLine.png" alt="">
        </div>
        <div class="text">
            <h2>Quem somos?</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!
            </p>
            <h2>Sobre a empresa</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            <h3>Nossos serviços</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed aspernatur, nemo rem voluptatum, vitae mollitia qui numquam voluptate natus nihil, sapiente voluptates neque commodi et id recusandae perferendis quas repellendus!</p>
            
        </div>
    </div>
</main>