<main >
    <div class="center">
        <div class="img">
            <img src="img/page-veterinario.jpg" alt="">
        </div>
        <div class="text">
            <h2>EQUIPE QUALIFICADA E EXPERIENTE</h2>
            <p>Nossos médicos veterinários são um dos maiores diferenciais do nosso serviço.
            Nestes mais de 25 anos de história, a Dra Michele Sandrault e o Dr. Luis Fernando foram responsáveis pelo atendimento de diversos atendimentos de risco com sucesso. Além de orientar e acompanhar o desenvolvimento dos mais de 8.000 clientes da clínica. Sempre com uma abordagem humana e de fácil entendimento, repleta de amor e carinho por nossos pacientes.
            Além disso, nossa equipe de banho e tosa é treinada para realizar a higiene dos animais com o máximo de carinho e atenção aos detalhes: sempre buscando por desconfortos ou possíveis sintomas de que o animal possa estar sofrendo de alguma doença de pele ou dores. Isto ajuda na prevenção de doenças e identifica sintomas ainda no início, garantindo uma vida mais saudável e tranquila para seu pet.</p>
            <h2>INFRAESTRUTURA COMPLETA E MODERNA</h2>
            <p>A Pet Pillow é uma clínica veterinária e hospital veterinário equipada para identificar e tratar as mais diversas doenças. Possuímos equipamentos de ponta para realização de exames laboratoriais diversos, inclusive exames de imagens como raio-x, ultrassom, ecocardiograma e endoscopia.</p>
            <h3>HOSPITAL VETERINÁRIO 24 HORAS</h3>
            <p>Na Pet Pillow o seu pet sempre será atendido com máxima eficiência e rapidez pela nossa equipe de veterinários. Somos uma clínica veterinária 24h garante que sempre haja um profissional qualificado pronto para atender casos emergenciais com toda a infraestrutura moderna da clínica. Em qualquer hora do dia ou da noite, conte com a equipe qualificada da Pet Pillow para cuidar do seu pet.
            Caso você já seja paciente da nossa clínica veterinária, nossos plantonistas terão acesso a todo histórico de atendimento médico do animal e irão passar um relatório completo ao veterinário titular do seu pet. Desta forma é possível prestar um atendimento completo e customizado para os pacientes mesmo em situações adversas.

            Venha conhecer a clínica e descubra por que somos uma das clínicas mais tradicionais no atendimento à cães e gatos. Temos uma promoção especial para novos clientes, basta clicar no link e se cadastrar.</p>
            
        </div>
    </div>
</main>