<div class="box_relatos">
    <div class="center">
        <h2>Meus relatos</h2>
        <div class="box_todos_relatos">
            <div class="btn_NR"><a href="/relatar-problema2">Fazer novo relato</a></div>
            <?php
            foreach($this->view->relatos as $relato){?>
            
            <div class="box_info_relato">
                <div>
                    <h3>Nível do problema: </h3><p><?=$relato['nivel']?></p>
                </div>
                <hr>
                <div>
                    <h3>Animal: </h3><p><?=$relato['animal']?></p>
                </div>
                <hr>
                <div class="D">
                    <h3>Descrição do problema: </h3><p><?=$relato['relato']?></p>
                </div>
                <hr>
                <div class="R">
                    <h3>Resposta:</h3>
                    <p><?php if(empty($relato['resposta'])){
                        echo 'Ainda não foi respondido';
                    }else{
                        echo $relato['resposta'];
                    }?></p>
                </div>
                <form action="/remover-relato" method="post">
                    <div class="btn_remover">
                        <button type="submit" name="id" value="<?=$relato['id']?>">Remover</button>
                    </div>
                </form>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
