<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/logo-Vetsline2.ico" type="image/x-icon">
    <script src="https://kit.fontawesome.com/d5c56409b7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/styleIndex.css">
    <?php
     if(isset($_GET['servicos']) || $this->view->page == 'sobreNos'){?>
     <link rel="stylesheet" href="css/stylePagesServicos.css">
    <?php } ?>
    <title>VetsLine</title>
</head>
<body id="body">
   <header id="header">
    <div class="center_header">
        <i id="menu" class="fas fa-bars"></i>
        
        <h1>
            <img src="img/VetsLine.png" alt="">
        </h1>
        <ul id="ul_nav">
            <li id="x"><i class="fas fa-times"></i></li>
            <li><a href="/home">Home</a></li>
            <li><a href="/sobre-nos">Sobre nós</a></li>
            <li><a href="/contato">Contato</a></li>
        </ul>
        <div class="container_btn_login">
            <div class="nome_user">
                <?php
                session_start();
                if(isset($_SESSION['nome'])){?>
                    <p>Olá</p>
                    <p><?=ucfirst($_SESSION['nome'])?></p>
               <?php }?>
            </div>
            <div id="btn_perfil">
                <i class="user fas fa-user-circle"></i>
                <i class="arrow fas fa-angle-down"></i>
           </div>
            <ul id="ul_perfil">
                <?php
                if(isset($_SESSION['nivel']) && $_SESSION['nivel'] == 2 || isset($_SESSION['nivel']) && $_SESSION['nivel'] == 3){?>
                    <li> <a href="/page-dashboard">Dashboard</a></li>
                    <li> <a href="/sair">Sair</a></li>
                <?php }else if(isset($_SESSION['nivel']) && $_SESSION['nivel'] == 1){?>
                    <li> <a href="/view-relatos">Ver meus relatos/Perfil</a></li>
                    <li> <a href="/sair">Sair</a></li>
                <?php }else{ ?>
                    <li> <a href="/entrar">Entrar</a></li>
                     <li> <a href="/cadastrar">Cadastrar</a></li>
                     <li> <a href="/entrar-admin">Entrar como admin</a></li>
                <?php } ?>
                
            </ul>
        </div>
    </div>
   </header>
   <?php
   $this->content();
   ?>
     <footer>
     <div>
        footer
     </div>
   </footer>
   <script src="/js/scriptsIndex.js"></script>
   </body>
</html>