<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/logo-Vetsline2.ico" type="image/x-icon">
    <script src="https://kit.fontawesome.com/d5c56409b7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/layout2.css">
    <title>Cadastrar</title>
</head>
<body>
    <?php
    $this->content();
    ?>
   
    <script src="/js/verSenha.js"></script>
</body>
</html>